### ISSUE TITLE
binance-connector vs binance-connector-ruby

### ISSUE THREAD

**Issue by mensfeld** [binance/binance-connector-ruby#1]
Hey there,

I wanted to raise to your attention a potential problem for your users related to this package. 

Your GH name of this repo is `binance-connector-ruby` but the gem name is: `binance-connector`. This is a mismatch that has been used previously to trick ppl into installing a malicious version of a package. `binance-connector-ruby` also exists and is released by someone else but they both claim Binance as an author. I would strongly recommend to either reaching out to the owner of `binance-connector-ruby` and reclaiming it or figuring out a way to make sure that the legit package is used for legit reasons.

Note: I am not saying that https://rubygems.org/gems/binance-connector-ruby is malicious in anyways. I'm just making a point on historical happenings in RubyGems + on the fact that there's a rather unfortunate name mismatch here.

ref https://rubygems.org/gems/binance-connector-ruby
ref https://rubygems.org/gems/binance-connector

**Comment by 2pd** [comment]
thank you for your suggestion.

- `binance-connector-ruby` was used in our another account for testing gem package release.
- `binance-connector` was used as we thought having `ruby` in the gem package title is a little bit redundant.  We are setting the language name in the github repo to distinguish it from multi languages.
   
We just made some changes and pump the version:

- `binance-connector-ruby` is the final gem name, released with latest source code.  It's under our Binance account ownership. The `README` is updated to give instruction of how to install this gem.
- `binance-connector` is also owned by us, but will NOT be updated later.

**Comment by mensfeld** [comment]
Thank you. That solves the problem. Also, you guys could update the `binance-connector` with a warning OR you could add a `binance-connector-ruby` as a dependency to simplify things. Anyhow closing as solves the issue. :pray:
