### ISSUE TITLE
Add `permissions` parameter to Exchange Information API

### ISSUE THREAD

**Issue by gPrado** [binance/binance-connector-ruby#19]
In the official docs (https://binance-docs.github.io/apidocs/spot/en/#exchange-information) there is the `permissions` parameters, but it is not available in this connector.
Would you accept a PR for this improvement?

**Comment by alplabin** [comment]
Thanks for proposing but no need. It has already been added in the version 1.5.2: https://github.com/binance/binance-connector-ruby/releases/tag/v1.5.2
